name    'gnubilafrance-redmine'
version '2.0.10'
author  'Baptiste Grenier'
license 'MIT'
project_page 'http://gnubila.fr'
source  'https://github.com/gnubila-france/puppet-redmine'
summary 'Puppet module for managing redmine'
description 'This module installs and manages redmine. Check README for details.'
dependency 'example42/puppi', '>= 2.0.0'
dependency 'alup/rbenv', '>= 1.2.0'
# dependency 'example42/monitor', '>= 2.0.0'
# dependency 'example42/firewall', '>= 2.0.0'
